site_name: UQ course

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
- Home:
  - Overview: index.md
- Lectures:
  - Introduction: lectures/index.md
  - Basics of probability: lectures/probability.md
  - Uncertainty quantification: lectures/uncertainty_quantification.md
  - Sensitivity analysis: lectures/sensitivity_analysis.md
  - Surrogate models: lectures/surrogate_models.md
  - Robust optimization: lectures/robust_optimization.md
- Exercises:
  - Introduction: exercises/index.md

plugins:
  - bibtex:
      bib_file: "docs/references.bib"

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
- footnotes
- toc:
    permalink: true
- pymdownx.snippets

extra_javascript:
- javascripts/mathjax.js
- https://polyfill.io/v3/polyfill.min.js?features=es6
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

use_directory_urls: false