site_name: UQ course
site_url: https://mdelozzo.github.io/uq-course/
copyright: >
  Copyright &copy; 2026 Matthias De Lozzo - 
  All rights reserved - 
  Reproduction prohibited without permission.

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode

nav:
- Home: index.md
- 1. Introduction: lectures/index.md
- 2. Basics of probability: lectures/probability.md
- 3. Uncertainty characterization: lectures/uncertainty_characterization.md
- 4. Uncertainty quantification: lectures/uncertainty_quantification.md
- 5. Uncertainty propagation: lectures/uncertainty_propagation.md
- 6. Sensitivity analysis: lectures/sensitivity_analysis.md
- 7. Surrogate models: lectures/surrogate_models.md
- 8. Robust optimization: lectures/robust_optimization.md
- Project: project.md

plugins:
  - bibtex:
      bib_file: "docs/references.bib"

markdown_extensions:
- admonition
- pymdownx.details
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
      - name: mermaid
        class: mermaid
- footnotes
- toc:
    permalink: true
- pymdownx.snippets

extra_javascript:
- javascripts/mathjax.js
- https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

use_directory_urls: false